# nat-gateway variables
variable "project_name" {}
variable "environment" {}
variable "public_subnet_az1" {}
variable "internet_gateway" {}
variable "public_subnet_az2" {}
variable "vpc_id" {}
variable "private_app_subnet_az1" {}
variable "private_data_subnet_az1" {}
variable "private_app_subnet_az2" {}
variable "private_data_subnet_az2" {}